version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: comment-spacings
