apiVersion: diagnose.diagnose.k8s.io/v1alpha1
kind: LogIntelligencePlatform
metadata:
  labels:
    app.kubernetes.io/name: kube-diagnose
    app.kubernetes.io/managed-by: kustomize
  name: logintelligenceplatform-sample
spec:
  llm:
    provider: google
    model: gemini-3.5-flash
    apiKeySecretRef:
      name: gemini-secret
      key: api-key
