## Append samples of your project ##
resources:
- diagnose_v1alpha1_logintelligenceplatform.yaml
- diagnose_v1alpha1_logwatchpolicy.yaml
- diagnose_v1alpha1_incident.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
